- src: https://github.com/msgqe/rhn-register.git
  scm: git
  name: rhn-register

- src: https://github.com/msgqe/rhn-subscribe.git
  scm: git
  name: rhn-subscribe

- src: https://github.com/msgqe/epel.git
  scm: git
  name: epel
